### ISSUE TITLE
Car veers to right

### ISSUE THREAD

**Issue by Joss-Steward** [Joss-Steward/FreescaleCup#1]
_Expected Behavior:_
Car is expected to follow track, avoiding the lines at both sides.

_Actual Behavior:_
The car veers wildly to the right while driving, going right over the line.

**Comment by ChrisHersh** [comment]
I think we should consider this a feature and make it as such

**Comment by Joss-Steward** [comment]
This is not fixed yet. Do not close it.

**Comment by redja150** [comment]
Can we close it now? the bug bugs me.

**Comment by Joss-Steward** [comment]
Oh fine.
